# =============================================================================
#  Copyright (c) Anon4You - https://github.com/Anon4You/dotfiles
#  Termux color scheme (~/.termux/colors.properties)
#
#  After editing, run:  termux-reload-settings
# =============================================================================

background=#0b0e1f
foreground=#e8e8f0
# black
color0=#1a1c27
color8=#42454f
# red
color1=#e34b7c
color9=#ff5c8a
# green
color2=#1fd48f
color10=#58f5ac
# yellow
color3=#e9c46a
color11=#ffe066
# blue
color4=#4cc9f0
color12=#70d7ff
# magenta
color5=#c77dff
color13=#d9a0ff
# cyan
color6=#2ec4b6
color14=#4fe3d4
# white
color7=#d6d6de
color15=#ffffff
